const mascotSVG=`
<svg viewBox="0 0 260 250" xmlns="http://www.w3.org/2000/svg" aria-label="小天線隊長">
  <g>
    <ellipse cx="132" cy="220" rx="69" ry="13" fill="#143b66" opacity=".09"/>
    <g transform="translate(23,77) rotate(-9)">
      <rect x="0" y="32" width="57" height="95" rx="25" fill="#1267d8"/>
      <rect x="8" y="40" width="41" height="70" rx="19" fill="#197df2"/>
      <path d="M18 79l11-9 4-15 6 13 15 2-13 8 3 15-12-10-14 7 5-12z" fill="white"/>
    </g>
    <path d="M82 184c-9 3-20 18-14 27 6 9 24 0 31-12" fill="#0a58b5"/>
    <path d="M171 187c12 4 24 17 19 27-5 10-25 2-34-12" fill="#0a58b5"/>
    <path d="M82 149c-19 5-31 20-24 31 7 12 25 0 36-10" fill="#78e0c3"/>
    <path d="M180 147c20 3 33 16 28 28-5 12-25 4-38-7" fill="#78e0c3"/>
    <circle cx="132" cy="124" r="75" fill="#84e6c8"/>
    <circle cx="112" cy="116" r="25" fill="white"/><circle cx="155" cy="116" r="25" fill="white"/>
    <ellipse cx="116" cy="118" rx="13" ry="18" fill="#143b66"/><ellipse cx="159" cy="118" rx="13" ry="18" fill="#143b66"/>
    <circle cx="120" cy="112" r="4" fill="white"/><circle cx="163" cy="112" r="4" fill="white"/>
    <ellipse cx="93" cy="150" rx="12" ry="7" fill="#ff99a8" opacity=".8"/><ellipse cx="174" cy="150" rx="12" ry="7" fill="#ff99a8" opacity=".8"/>
    <path d="M119 145c4 20 27 24 34 2 2-7-4-11-16-11-12 0-20 2-18 9z" fill="#6b1e2d"/><path d="M128 154c8-7 18-4 20 1-6 9-15 11-20-1z" fill="#ff8d9d"/>
    <path d="M107 54C99 28 89 18 80 22" stroke="#55cdb2" stroke-width="11" stroke-linecap="round" fill="none"/><circle cx="78" cy="21" r="13" fill="#78e0c3"/>
    <path d="M159 53c8-27 19-35 28-30" stroke="#55cdb2" stroke-width="11" stroke-linecap="round" fill="none"/><circle cx="190" cy="23" r="13" fill="#78e0c3"/>
  </g>
</svg>`;
const state={mode:"smart",companion:"friends",days:5,budget:2,interests:[],concern:"none",visited:[],excluded:[],pool:[],selected:null,result:null};\nconst memStore={}; function storeGet(k,d="[]"){try{return localStorage.getItem(k)||d}catch(e){return memStore[k]||d}} function storeSet(k,v){try{localStorage.setItem(k,v)}catch(e){memStore[k]=v}}
const places=[
{id:"jp-fukuoka",country:"日本",zh:"福岡",en:"Fukuoka",flag:"🇯🇵",days:[3,5],budget:2,flight:3.7,solo:5,couple:4,friends:5,family:4,elderly:4,food:5,shopping:4,photo:4,beach:2,nature:3,hotSpring:4,culture:4,relax:5,walk:2,crowd:2,heat:2,language:2,tags:["4–5日啱玩","美食多","交通方便"]},
{id:"jp-tokyo",country:"日本",zh:"東京",en:"Tokyo",flag:"🇯🇵",days:[4,7],budget:3,flight:4.5,solo:5,couple:5,friends:5,family:5,elderly:3,food:5,shopping:5,photo:5,beach:1,nature:2,hotSpring:2,culture:5,relax:2,walk:4,crowd:5,heat:3,language:3,tags:["城市探索","Shopping","美食"]},
{id:"jp-osaka",country:"日本",zh:"大阪",en:"Osaka",flag:"🇯🇵",days:[4,6],budget:3,flight:4.2,solo:5,couple:4,friends:5,family:5,elderly:3,food:5,shopping:5,photo:4,beach:1,nature:2,hotSpring:2,culture:4,relax:3,walk:4,crowd:4,heat:3,language:3,tags:["朋友啱玩","食買玩","交通方便"]},
{id:"jp-sapporo",country:"日本",zh:"札幌",en:"Sapporo",flag:"🇯🇵",days:[4,6],budget:3,flight:5.2,solo:4,couple:5,friends:4,family:4,elderly:3,food:5,shopping:3,photo:5,beach:1,nature:5,hotSpring:4,culture:3,relax:4,walk:3,crowd:2,heat:1,language:2,tags:["雪景","美食","自然"]},
{id:"jp-okinawa",country:"日本",zh:"沖繩",en:"Okinawa",flag:"🇯🇵",days:[4,6],budget:3,flight:2.8,solo:3,couple:5,friends:5,family:5,elderly:4,food:4,shopping:2,photo:5,beach:5,nature:5,hotSpring:2,culture:3,relax:5,walk:2,crowd:2,heat:4,language:2,tags:["海島","放鬆","親子"]},
{id:"kr-seoul",country:"韓國",zh:"首爾",en:"Seoul",flag:"🇰🇷",days:[4,6],budget:2,flight:3.7,solo:5,couple:5,friends:5,family:4,elderly:2,food:5,shopping:5,photo:5,beach:1,nature:2,hotSpring:2,culture:4,relax:2,walk:4,crowd:5,heat:3,language:3,tags:["Shopping","Cafe","夜生活"]},
{id:"kr-busan",country:"韓國",zh:"釜山",en:"Busan",flag:"🇰🇷",days:[3,5],budget:2,flight:3.5,solo:4,couple:5,friends:5,family:4,elderly:3,food:5,shopping:3,photo:5,beach:5,nature:4,hotSpring:3,culture:3,relax:4,walk:3,crowd:3,heat:3,language:2,tags:["海景","美食","節奏舒服"]},
{id:"tw-taipei",country:"台灣",zh:"台北",en:"Taipei",flag:"🇹🇼",days:[3,5],budget:2,flight:1.9,solo:5,couple:4,friends:5,family:5,elderly:5,food:5,shopping:4,photo:4,beach:1,nature:3,hotSpring:4,culture:4,relax:4,walk:2,crowd:3,heat:3,language:1,tags:["短途","美食","長者友善"]},
{id:"tw-tainan",country:"台灣",zh:"台南",en:"Tainan",flag:"🇹🇼",days:[3,5],budget:1,flight:2.3,solo:4,couple:5,friends:4,family:4,elderly:4,food:5,shopping:2,photo:5,beach:2,nature:3,hotSpring:1,culture:5,relax:5,walk:2,crowd:2,heat:4,language:1,tags:["慢活","古城","小食"]},
{id:"th-bangkok",country:"泰國",zh:"曼谷",en:"Bangkok",flag:"🇹🇭",days:[4,6],budget:1,flight:3,solo:4,couple:5,friends:5,family:4,elderly:3,food:5,shopping:5,photo:4,beach:1,nature:1,hotSpring:1,culture:4,relax:3,walk:3,crowd:4,heat:5,language:3,tags:["性價比","美食","Shopping"]},
{id:"th-chiangmai",country:"泰國",zh:"清邁",en:"Chiang Mai",flag:"🇹🇭",days:[4,6],budget:1,flight:3.2,solo:5,couple:5,friends:4,family:4,elderly:4,food:4,shopping:2,photo:5,beach:1,nature:5,hotSpring:3,culture:5,relax:5,walk:2,crowd:2,heat:4,language:3,tags:["放空","自然","文青"]},
{id:"th-phuket",country:"泰國",zh:"布吉",en:"Phuket",flag:"🇹🇭",days:[4,6],budget:2,flight:3.6,solo:3,couple:5,friends:5,family:4,elderly:3,food:4,shopping:2,photo:5,beach:5,nature:5,hotSpring:1,culture:2,relax:5,walk:2,crowd:3,heat:5,language:3,tags:["海灘","Resort","朋友"]},
{id:"vn-danang",country:"越南",zh:"峴港",en:"Da Nang",flag:"🇻🇳",days:[4,6],budget:1,flight:2,solo:4,couple:5,friends:5,family:4,elderly:4,food:4,shopping:2,photo:5,beach:5,nature:4,hotSpring:1,culture:3,relax:5,walk:2,crowd:2,heat:5,language:3,tags:["海灘","抵玩","放鬆"]},
{id:"sg-singapore",country:"新加坡",zh:"新加坡",en:"Singapore",flag:"🇸🇬",days:[3,5],budget:3,flight:3.8,solo:5,couple:4,friends:4,family:5,elderly:5,food:5,shopping:5,photo:5,beach:2,nature:3,hotSpring:1,culture:4,relax:3,walk:2,crowd:3,heat:5,language:1,tags:["交通超方便","親子","美食"]},
{id:"my-penang",country:"馬來西亞",zh:"檳城",en:"Penang",flag:"🇲🇾",days:[3,5],budget:1,flight:3.8,solo:4,couple:5,friends:4,family:4,elderly:4,food:5,shopping:2,photo:5,beach:3,nature:3,hotSpring:1,culture:5,relax:5,walk:2,crowd:2,heat:5,language:2,tags:["街頭美食","慢活","文化"]},
{id:"id-bali",country:"印尼",zh:"峇里島",en:"Bali",flag:"🇮🇩",days:[5,8],budget:2,flight:5,solo:4,couple:5,friends:5,family:4,elderly:3,food:4,shopping:2,photo:5,beach:5,nature:5,hotSpring:1,culture:4,relax:5,walk:2,crowd:3,heat:5,language:3,tags:["Resort","浪漫","放空"]},
{id:"au-melbourne",country:"澳洲",zh:"墨爾本",en:"Melbourne",flag:"🇦🇺",days:[6,9],budget:4,flight:9.2,solo:5,couple:5,friends:4,family:4,elderly:4,food:5,shopping:4,photo:5,beach:3,nature:5,hotSpring:1,culture:5,relax:4,walk:3,crowd:2,heat:2,language:1,tags:["Cafe","Road Trip","文化"]},
{id:"ca-vancouver",country:"加拿大",zh:"溫哥華",en:"Vancouver",flag:"🇨🇦",days:[7,10],budget:4,flight:12,solo:5,couple:5,friends:4,family:4,elderly:4,food:4,shopping:3,photo:5,beach:3,nature:5,hotSpring:1,culture:3,relax:4,walk:2,crowd:2,heat:1,language:1,tags:["自然","城市","輕鬆"]}
];
const companions=[["solo","🧍","自己","想點玩就點玩","mint"],["couple","💞","情侶","二人世界","pink"],["friends","👯","朋友","一齊食、一齊玩","yellow"],["family","👨‍👩‍👧","家人","一家人慢慢玩","mint"],["kids","🧒","親子","小朋友都要開心","yellow"],["elderly","👵","三代同堂","長者舒適度優先","purple"]];
const interests=[["food","🍜","美食","#ff6c5c"],["shopping","🛍️","Shopping","#9a68ef"],["photo","📷","打卡","#42a6f5"],["beach","🏝️","海灘","#31c78d"],["nature","🌿","大自然","#36c66d"],["hotSpring","♨️","溫泉","#ff975c"],["culture","🏛️","文化歷史","#8a72e8"],["relax","😴","放空","#67cce8"]];
const memories=["東京","大阪","首爾","台北","曼谷","新加坡","福岡","沖繩","釜山","峇里島"];
const colors=[["#ffd447","#ff9b45"],["#65c8ff","#0867f2"],["#ff79af","#ff5276"],["#5ddaa1","#20b96d"],["#9a68ef","#6d47cf"],["#ff765d","#ff9b45"],["#2c93ff","#0762d8"],["#f47bbb","#d94eb1"],["#f9c739","#f09639"],["#a376ee","#7549c5"],["#49d08d","#1fae78"],["#57b5ff","#3972e4"]];
const hints=["✈️","🌴","🌸","🌲","🏯","🍜","❄️","♥","☀️","🏙️","🎈","🚢"];
const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
function go(id){$$(".screen").forEach(x=>x.classList.remove("active"));$("#"+id).classList.add("active");scrollTo({top:0,behavior:"smooth"})}
function toast(msg){const t=$("#toast");t.textContent=msg;t.classList.add("show");clearTimeout(toast._);toast._=setTimeout(()=>t.classList.remove("show"),1200)}
function setupProgress(){$$(".progress").forEach(p=>{const n=p.dataset.progress+"%";p.style.setProperty("--p",n);p.querySelector("i").style.width=n;p.querySelector("b").style.left=n})}
function renderMascots(){$$("[data-mascot]").forEach(x=>x.innerHTML=mascotSVG)}
function renderCompanions(){$("#companionGrid").innerHTML=companions.map(([v,e,t,s,c])=>`<button class="choice ${c} ${state.companion===v?"active":""}" data-companion="${v}"><strong>${e} ${t}</strong><small>${s}</small></button>`).join("")}
function renderBasics(){const d=[[3,"1–3日","#65c8ff"],[5,"4–5日","#0867f2"],[7,"6–8日","#9a68ef"],[10,"9日+","#35c76c"]],b=[[1,"HK$3K以下","#35c76c"],[2,"HK$3K–6K","#0867f2"],[3,"HK$6K–10K","#9a68ef"],[4,"HK$10K+","#ff4f61"]];$("#days").innerHTML=d.map(x=>`<button class="chip ${state.days===x[0]?"active":""}" style="--chip:${x[2]}" data-days="${x[0]}">${x[1]}</button>`).join("");$("#budget").innerHTML=b.map(x=>`<button class="chip ${state.budget===x[0]?"active":""}" style="--chip:${x[2]}" data-budget="${x[0]}">${x[1]}</button>`).join("")}
function renderInterests(){$("#interests").innerHTML=interests.map(([v,e,t,c],i)=>`<button class="interest ${state.interests.includes(v)?"active":""}" style="--c:${c};--rot:${i%2?"-1deg":"1deg"}" data-interest="${v}"><span class="emoji">${e}</span><strong>${t}</strong></button>`).join("")}
function renderConcerns(){let set=[["budget","💸","唔想太貴"],["crowd","👥","唔想太迫"],["short","✈️","唔想飛太耐"],["none","✨","冇特別"]];if(state.companion==="solo")set=[["short","✈️","唔想飛太耐"],["language","🗣️","溝通太麻煩"],["crowd","👥","太多人太迫"],["none","✨","冇特別"]];if(state.companion==="elderly")set=[["walk","🚶","唔想行太多"],["short","✈️","唔想飛太耐"],["crowd","👥","怕太多人"],["none","✨","冇特別"]];if(state.companion==="kids")set=[["short","✈️","唔想飛太耐"],["heat","🥵","唔想太熱"],["crowd","👥","怕太多人"],["none","✨","冇特別"]];$("#concerns").innerHTML=set.map(([v,e,t],i)=>`<button class="choice ${["pink","yellow","purple","mint"][i]} ${state.concern===v?"active":""}" data-concern="${v}"><strong>${e} ${t}</strong><small>${v==="none"?"保持多啲驚喜":"我會幫你優先避開"}</small></button>`).join("")}
function renderMemory(){$("#memoryList").innerHTML=memories.map(x=>{let c=state.excluded.includes(x)?"excluded":state.visited.includes(x)?"visited":"";let p=state.excluded.includes(x)?"🚫 ":state.visited.includes(x)?"✓ ":"";return `<button class="memory-pill ${c}" data-memory="${x}">${p}${x}</button>`}).join("")}
function score(p){if(state.excluded.includes(p.zh))return-9999;let s=0;s+=state.days>=p.days[0]&&state.days<=p.days[1]?24:Math.max(-16,12-Math.abs(state.days-(p.days[0]+p.days[1])/2)*4);s+=14-Math.abs(state.budget-p.budget)*5;const cm={solo:"solo",couple:"couple",friends:"friends",family:"family",kids:"family",elderly:"elderly"};s+=(p[cm[state.companion]]||3)*4;state.interests.forEach(k=>s+=(p[k]||0)*6);if(state.concern==="short")s-=Math.max(0,p.flight-4)*7;if(state.concern==="walk")s-=p.walk*6;if(state.concern==="crowd")s-=p.crowd*5;if(state.concern==="heat")s-=p.heat*5;if(state.concern==="budget")s-=p.budget*5;if(state.concern==="language")s-=p.language*4;if(state.visited.includes(p.zh))s-=38;const recent=JSON.parse(storeGet("flw_recent")||"[]"),ix=recent.indexOf(p.id);if(ix>=0)s-=Math.max(10,36-ix*4);return s+Math.random()*10}
function buildPool(fast=false){go("loading");const msgs=["先睇旅伴、日數同預算…","再睇你最想玩啲乜…","避開最近成日出現嘅地方…","加少少估你唔到嘅驚喜…","得喇！準備揀盲盒 ✨"];let i=0;$("#loadingText").textContent=msgs[0];$("#loadFill").style.width="10%";const timer=setInterval(()=>{i=Math.min(i+1,msgs.length-1);$("#loadingText").textContent=msgs[i];$("#loadFill").style.width=(15+i*20)+"%"},fast?150:300);setTimeout(()=>{clearInterval(timer);let ranked=places.map(p=>({p,s:score(p)})).filter(x=>x.s>-9000).sort((a,b)=>b.s-a.s),chosen=[],cc={};for(const x of ranked){if((cc[x.p.country]||0)>=3)continue;chosen.push(x.p);cc[x.p.country]=(cc[x.p.country]||0)+1;if(chosen.length>=12)break}if(chosen.length<9)ranked.forEach(x=>{if(!chosen.includes(x.p)&&chosen.length<12)chosen.push(x.p)});state.pool=chosen.sort(()=>Math.random()-.5);renderBoxes();$("#poolCount").textContent=state.pool.length+" 個";$("#partyNote").hidden=!(state.mode==="group"||["friends","couple","family","kids","elderly"].includes(state.companion));go("boxes")},fast?650:1450)}
function renderBoxes(){$("#boxGrid").innerHTML=state.pool.map((p,i)=>{const [a,b]=colors[i%colors.length];return `<button class="blindbox" style="background:linear-gradient(145deg,${a},${b});animation-delay:-${(i*.31)%3}s" data-box="${i}">?<span class="hint">${hints[i%hints.length]}</span></button>`}).join("")}
function selectBox(i,el){$$(".blindbox").forEach(x=>x.classList.remove("selected"));el.classList.add("selected");state.selected=i;const [a,b]=colors[i%colors.length];$("#pickedBox").style.background=`linear-gradient(145deg,${a},${b})`;$("#confirmSheet").classList.add("show");navigator.vibrate?.(15)}
function openSelected(){$("#confirmSheet").classList.remove("show");$("#reveal").classList.add("show");const seq=["3…","2…","1…","飛啦喂！"];let i=0;$("#countdown").textContent=seq[0];const timer=setInterval(()=>{i++;$("#countdown").textContent=seq[Math.min(i,3)];if(i>=3)clearInterval(timer)},450);setTimeout(()=>{state.result=state.pool[state.selected];let r=JSON.parse(storeGet("flw_recent")||"[]");r=[state.result.id,...r.filter(x=>x!==state.result.id)].slice(0,12);storeSet("flw_recent",JSON.stringify(r));renderResult();$("#reveal").classList.remove("show");confetti();go("result")},2150)}
function renderResult(){const p=state.result;$("#resultFlag").textContent=p.flag;$("#resultCity").textContent=p.zh;$("#resultEn").textContent=p.en;$("#resultTags").innerHTML=p.tags.map(t=>`<span class="tag">${t}</span>`).join("");const rs=[];if(state.days>=p.days[0]&&state.days<=p.days[1])rs.push(`你揀咗 <b>${state.days<=3?"1–3":state.days<=5?"4–5":state.days<=8?"6–8":"9+"} 日</b>，呢個目的地嘅節奏同日數幾吻合。`);if(state.interests.includes("food")&&p.food>=4)rs.push("你今次想 <b>食好嘢</b>，呢度嘅美食選擇夠多。");if(state.interests.includes("relax")&&p.relax>=4)rs.push("你想 <b>放鬆</b>，呢度較容易安排成舒服唔趕嘅旅程。");if(state.interests.includes("beach")&&p.beach>=4)rs.push("你揀咗 <b>海灘</b>，呢度有足夠陽光海岸感。");if(state.interests.includes("shopping")&&p.shopping>=4)rs.push("你想 <b>Shopping</b>，呢度有足夠購物同城市體驗。");if(state.concern==="walk"&&p.walk<=2)rs.push("你唔想 <b>行到腳軟</b>，呢個選擇相對容易安排得輕鬆。");if(state.concern==="short"&&p.flight<=5)rs.push("你唔想 <b>飛太耐</b>，呢個航程相對容易接受。");if(state.companion==="elderly"&&p.elderly>=4)rs.push("你有 <b>長者同行</b>，呢個目的地較容易安排交通同休息節奏。");if(!rs.length)rs.push(`綜合你嘅日數、預算、旅伴同玩法，<b>${p.zh}</b> 喺今次候選池入面整體配對得幾好。`);$("#reasons").innerHTML=rs.slice(0,4).map((r,i)=>`<div class="reason"><span>${["✨","🧭","💙","🌍"][i]}</span><div>${r}</div></div>`).join("")}
async function shareResult(){if(!state.result)return;const text=`飛啦喂！我抽到 ${state.result.zh} ${state.result.flag} ✈️\nYou only live once, 人生得一次，仲等咩？飛啦喂！`;if(navigator.share){try{await navigator.share({title:"飛啦喂！",text})}catch(e){}}else{await navigator.clipboard?.writeText(text);toast("已複製分享文字")}}
function confetti(){const cs=["#0867f2","#ffd447","#ff79af","#35c76c","#9b6aef","#ff4f61"];for(let i=0;i<42;i++){const e=document.createElement("i");e.className="confetti";e.style.left=Math.random()*100+"vw";e.style.background=cs[i%cs.length];e.style.animationDelay=Math.random()*.45+"s";document.body.appendChild(e);setTimeout(()=>e.remove(),2600)}}
document.addEventListener("click",e=>{const goBtn=e.target.closest("[data-go]");if(goBtn)go(goBtn.dataset.go);const m=e.target.closest("[data-mode]");if(m){state.mode=m.dataset.mode;if(state.mode==="random"){state.days=5;state.budget=2;state.interests=["food","relax"];buildPool()}else go("companion")}const c=e.target.closest("[data-companion]");if(c){state.companion=c.dataset.companion;renderCompanions()}const d=e.target.closest("[data-days]");if(d){state.days=+d.dataset.days;renderBasics()}const b=e.target.closest("[data-budget]");if(b){state.budget=+b.dataset.budget;renderBasics()}const it=e.target.closest("[data-interest]");if(it){const v=it.dataset.interest,i=state.interests.indexOf(v);if(i>=0)state.interests.splice(i,1);else if(state.interests.length<4)state.interests.push(v);else return toast("最多揀 4 樣就夠啦 ✋");renderInterests()}const co=e.target.closest("[data-concern]");if(co){state.concern=co.dataset.concern;renderConcerns()}const mem=e.target.closest("[data-memory]");if(mem){const x=mem.dataset.memory;if(!state.visited.includes(x)&&!state.excluded.includes(x))state.visited.push(x);else if(state.visited.includes(x)){state.visited=state.visited.filter(v=>v!==x);state.excluded.push(x)}else state.excluded=state.excluded.filter(v=>v!==x);renderMemory()}const box=e.target.closest("[data-box]");if(box)selectBox(+box.dataset.box,box)});
$("#companionNext").onclick=()=>go("basics");$("#basicsNext").onclick=()=>go("vibe");$("#vibeNext").onclick=()=>{if(!state.interests.length)return toast("揀至少一樣先 ✨");if(state.mode==="quick")buildPool();else{renderConcerns();go("concern")}};$("#concernNext").onclick=()=>go("memory");$("#skipMemory").onclick=()=>buildPool();$("#matchNow").onclick=()=>buildPool();$("#reshuffle").onclick=()=>buildPool(true);$("#lookAgain").onclick=()=>$("#confirmSheet").classList.remove("show");$("#openBox").onclick=openSelected;$("#reroll").onclick=()=>buildPool(true);$("#share").onclick=shareResult;$("#shareTop").onclick=shareResult;$("#save").onclick=e=>{if(!state.result)return;let a=JSON.parse(storeGet("flw_saved")||"[]");if(!a.includes(state.result.id))a.push(state.result.id);storeSet("flw_saved",JSON.stringify(a));e.target.textContent="✓ 已收藏";toast("幫你記低咗 ❤️")};
renderMascots();setupProgress();renderCompanions();renderBasics();renderInterests();renderConcerns();renderMemory();